config/routes.rb
Rails.application.routes.draw do

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :numbers
  resources :participation_tokens
  resources :polls

  root to: 'polls#index'

  get 'polls/:id/participate/:participation_token', to: 'polls#participate', as: 'participitation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/number.rb
class Number < ApplicationRecord
  belongs_to :poll
  validates :poll, :hours, presence: true
  validates_with PollValidator
end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController
  skip_before_action :authorize, only: [:create, :new]
  before_action :set_number, only: [:show, :edit, :update, :destroy]

  # GET /numbers
  # GET /numbers.json
  def index
    @numbers = Number.all
  end

  # GET /numbers/1
  # GET /numbers/1.json
  def show
    @poll = @number.poll
  end

  # GET /numbers/new
  def new
    @number = Number.new
  end

  # GET /numbers/1/edit
  def edit
  end

  # POST /numbers
  # POST /numbers.json
  def create
    @number = Number.new(number_params)
    respond_to do |format|
      if @number.save
        format.html { redirect_to @number.poll, notice: I18n.t('thank_you') }
        format.json { render :show, status: :created, location: @number }
      else
        format.html { redirect_to poll_path(@number.poll), notice: I18n.t('.invalid_participation_url') }
        format.json { render json: @number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /numbers/1
  # PATCH/PUT /numbers/1.json
  def update
    respond_to do |format|
      if @number.update(number_params)
        format.html { redirect_to @number, notice: 'Number was successfully updated.' }
        format.json { render :show, status: :ok, location: @number }
      else
        format.html { render :edit }
        format.json { render json: @number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /numbers/1
  # DELETE /numbers/1.json
  def destroy
    @number.destroy
    respond_to do |format|
      format.html { redirect_to numbers_url, notice: 'Number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_number
      @number = Number.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def number_params
      params.require(:number).permit(:hours, :hash, :poll_id, :participation_key)
    end
end

app/helpers/numbers_helper.rb
module NumbersHelper
end

app/views/numbers/_form.html.erb
<%= form_for(number) do |f| %>
  <% if number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(number.errors.count, "error") %> prohibited this number from being saved:</h2>

      <ul>
      <% number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hours %>
    <%= f.number_field :hours %>
  </div>

    <%= f.hidden_field :participation_key %>
    <%= f.hidden_field :poll_id %>

  <div class="actions">
    <%= f.submit t('.submit')%>
  </div>
<% end %>

app/views/numbers/edit.html.erb
<h1>Editing Number</h1>

<%= render 'form', number: @number %>

<%= link_to 'Show', @number %> |
<%= link_to 'Back', numbers_path %>

app/views/numbers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Numbers</h1>

<table>
  <thead>
    <tr>
      <th>Hours</th>
      <th>Hash</th>
      <th>Poll</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @numbers.each do |number| %>
      <tr>
        <td><%= number.hours %></td>
        <td><%= number.hash %></td>
        <td><%= number.poll %></td>
        <td><%= link_to 'Show', number %></td>
        <td><%= link_to 'Edit', edit_number_path(number) %></td>
        <td><%= link_to 'Destroy', number, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Number', new_number_path %>

app/views/numbers/new.html.erb
<h1>New Answer to Poll: <%= @poll.name %></h1>

<%= render 'numbers/form', number: @number %>

<%= link_to 'Back', numbers_path %>

app/views/numbers/show.html.erb
<h1><%= @poll.name %></h1>
<p id="notice"><%= notice %></p>
<p>Your answer: </p>
<p>
  <strong>Hours:</strong>
  <%= @number.hours %>
</p>

<p>
  <strong>View Poll:</strong>
  <%= link_to @poll.name, @poll  %>
</p>

<%= link_to 'Edit', edit_number_path(@number) %> |
<%= link_to 'Back', numbers_path %>