config/routes.rb
Rails.application.routes.draw do

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :numbers
  resources :participation_tokens
  resources :polls

  root to: 'polls#index'

  get 'polls/:id/participate/:participation_token', to: 'polls#participate', as: 'participitation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/poll.rb
class Poll < ApplicationRecord
  has_many :numbers, dependent: :destroy
  has_many :participation_tokens, dependent: :destroy
  after_create :generate_participation_tokens

  validates :name, :participants, presence: true
  validates :participants, numericality: true

  def number_histogram
    results = numbers.map(&:hours)
    #byebug
    max = results.empty? ? 0 : results.max + 1
    histogram = Array.new(max,0)
    results.each {|r| histogram[r] = histogram[r]+1}
    histogram
  end

  def generate_participation_tokens
    participants.times do
      participation_tokens.create(participation_key: SecureRandom.urlsafe_base64)
    end
  end

  def valid_participation_token?(token)
    participation_tokens.where(participation_key: token).any?
  end

  def register_answer(record)
    tokens = participation_tokens.where(participation_key: record.participation_key)
    if tokens.any?
      tokens.first.destroy
      return true
    else
      return false
    end
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  skip_before_action :authorize, only: [:participate, :show]
  include PollsHelper
  before_action :set_poll, only: [:show, :edit, :update, :destroy, :participate]

  def participate

    respond_to do |format|
      if (pt = valid_partication_token).nil?
        format.html { redirect_to @poll, notice: I18n.t('.invalid_participation_url') }
      else
        @number = @poll.numbers.build(participation_key: pt.participation_key)
        format.html { render "numbers/new"}
      end
    end
  end

  def valid_partication_token
    key = params['participation_token']
    return nil unless key
    tokens = @poll.participation_tokens.where(participation_key: key)
    return nil if tokens.empty?
    tokens.first
  end

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
    @participation_urls = participation_urls(@poll)
    @answers = @poll.number_histogram
  end

  # GET /polls/new
  def new
    @poll = Poll.new(open: true, answer_type: "Number", participants: 30)
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:name, :description, :instant_result, :public_result, :open, :answer_type, :participants)
    end
end

app/helpers/polls_helper.rb
module PollsHelper
  def participation_urls(poll)
    poll.participation_tokens.map do | participant |
       participitation_url(poll,participant.participation_key)
    end
  end
#  def participation_paths(poll)
#    poll.participation_tokens.map do | participant |
#       participitation_path(poll,participant.participation_key)
#    end
#  end
end

app/views/polls/_form.html.erb
<%= form_for(poll) do |f| %>
  <% if poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% poll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t('.name') %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :participants %>
    <%= f.number_field :participants %>
  </div>

<table ><tr>
  <td>
  <div class="field">
    <%= f.label :instant_result %>
    <%= f.check_box :instant_result %>
  </div>
</td><td>
  <div class="field">
    <%= f.label :public_result %>
    <%= f.check_box :public_result %>
  </div>
</td><td>
  <div class="field">
    <%= f.label :open %>
    <%= f.check_box :open %>
  </div>
</td></tr></table>
<!--
  <div class="field">
    <%= f.label :answer_type %>
    <%= f.text_field :answer_type %>
  </div>
-->


  <div class="actions">
    <%= f.submit t('.submit') %>
  </div>
<% end %>

app/views/polls/edit.html.erb
<h1>Editing Poll</h1>

<%= render 'form', poll: @poll %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Polls</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Instant result</th>
      <th>Public result</th>
      <th>Open</th>
      <th>Answer type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= poll.name %></td>
        <td><%= poll.description %></td>
        <td><%= poll.instant_result %></td>
        <td><%= poll.public_result %></td>
        <td><%= poll.open %></td>
        <td><%= poll.answer_type %></td>
        <td><%= link_to 'Show', poll %></td>
        <td><%= link_to 'Edit', edit_poll_path(poll) %></td>
        <td><%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poll', new_poll_path %>

app/views/polls/new.html.erb
<h1>New Poll</h1>

<%= render 'form', poll: @poll %>

<%= link_to 'Back', polls_path %>

app/views/polls/participate.html.erb
<%= t('invalid_participation_url') %>

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @poll.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @poll.description %>
</p>

<p>
  <strong>Instant result:</strong>
  <%= @poll.instant_result %>
</p>

<p>
  <strong>Public result:</strong>
  <%= @poll.public_result %>
</p>

<p>
  <strong>Open:</strong>
  <%= @poll.open %>
</p>
<!--
<p>
  <strong>Answer type:</strong>
  <%= @poll.answer_type %>
</p>
-->

<h3> Results </h3>
<table border = "1"><tr>
  <% for i in 0..@answers.size-1 do %>
  <th><%= i %></th>
  <% end %>
</tr><tr>
  <% for i in 0..@answers.size-1 do %>
  <th><%= @answers[i]%></th>
  <% end %>
</tr>
</table>

<% if logged_in? %>
<% if @poll.open %>
<hr>
<h2>Participation Keys</h2>
Please send these participation links to the participants:

<pre>
  <% @participation_urls.each do | url | %>
<%= url %>
  <% end %>
</pre>
<% end %>
<hr/>
<%= link_to 'Edit', edit_poll_path(@poll) %> |
<%= link_to 'Back', polls_path %>

<% end %>