config/routes.rb
Rails.application.routes.draw do

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :numbers
  resources :participation_tokens
  resources :polls

  root to: 'polls#index'

  get 'polls/:id/participate/:participation_token', to: 'polls#participate', as: 'participitation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/participation_token.rb
class ParticipationToken < ApplicationRecord
  belongs_to :poll
end

app/controllers/participation_tokens_controller.rb
class ParticipationTokensController < ApplicationController
  before_action :set_participation_token, only: [:show, :edit, :update, :destroy]

  # GET /participation_tokens
  # GET /participation_tokens.json
  def index
    @participation_tokens = ParticipationToken.all
  end

  # GET /participation_tokens/1
  # GET /participation_tokens/1.json
  def show
  end

  # GET /participation_tokens/new
  def new
    @participation_token = ParticipationToken.new
  end

  # GET /participation_tokens/1/edit
  def edit
  end

  # POST /participation_tokens
  # POST /participation_tokens.json
  def create
    @participation_token = ParticipationToken.new(participation_token_params)

    respond_to do |format|
      if @participation_token.save
        format.html { redirect_to @participation_token, notice: 'Participation token was successfully created.' }
        format.json { render :show, status: :created, location: @participation_token }
      else
        format.html { render :new }
        format.json { render json: @participation_token.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participation_tokens/1
  # PATCH/PUT /participation_tokens/1.json
  def update
    respond_to do |format|
      if @participation_token.update(participation_token_params)
        format.html { redirect_to @participation_token, notice: 'Participation token was successfully updated.' }
        format.json { render :show, status: :ok, location: @participation_token }
      else
        format.html { render :edit }
        format.json { render json: @participation_token.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participation_tokens/1
  # DELETE /participation_tokens/1.json
  def destroy
    @participation_token.destroy
    respond_to do |format|
      format.html { redirect_to participation_tokens_url, notice: 'Participation token was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participation_token
      @participation_token = ParticipationToken.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participation_token_params
      params.require(:participation_token).permit(:hash, :poll_id)
    end
end

app/helpers/participation_tokens_helper.rb
module ParticipationTokensHelper
end

app/views/participation_tokens/_form.html.erb
<%= form_for(participation_token) do |f| %>
  <% if participation_token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participation_token.errors.count, "error") %> prohibited this participation_token from being saved:</h2>

      <ul>
      <% participation_token.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hash %>
    <%= f.text_field :hash %>
  </div>

  <div class="field">
    <%= f.label :poll_id %>
    <%= f.text_field :poll_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participation_tokens/edit.html.erb
<h1>Editing Participation Token</h1>

<%= render 'form', participation_token: @participation_token %>

<%= link_to 'Show', @participation_token %> |
<%= link_to 'Back', participation_tokens_path %>

app/views/participation_tokens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Participation Tokens</h1>

<table>
  <thead>
    <tr>
      <th>Hash</th>
      <th>Poll</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participation_tokens.each do |participation_token| %>
      <tr>
        <td><%= participation_token.hash %></td>
        <td><%= participation_token.poll %></td>
        <td><%= link_to 'Show', participation_token %></td>
        <td><%= link_to 'Edit', edit_participation_token_path(participation_token) %></td>
        <td><%= link_to 'Destroy', participation_token, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participation Token', new_participation_token_path %>

app/views/participation_tokens/new.html.erb
<h1>New Participation Token</h1>

<%= render 'form', participation_token: @participation_token %>

<%= link_to 'Back', participation_tokens_path %>

app/views/participation_tokens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hash:</strong>
  <%= @participation_token.hash %>
</p>

<p>
  <strong>Poll:</strong>
  <%= @participation_token.poll %>
</p>

<%= link_to 'Edit', edit_participation_token_path(@participation_token) %> |
<%= link_to 'Back', participation_tokens_path %>